### ISSUE TITLE
Error in ais.js

### ISSUE THREAD

**Issue by tkurki** [SignalK/n2k-signalk#218]
Cannot read property 'length' of undefined at hasAnyKeys (/home/pi/.signalk/node_modules/signalk-to-nmea2000/conversions/ais.js:379:52) at Object.callback (/home/pi/.signalk/node_modules/signalk-to-nmea2000/conversions/ais.js:61:25) at FullSignalK.app.signalk.on (/home/pi/.signalk/node_modules/signalk-to-nmea2000/index.js:238:55)

**Comment by tkurki** [comment]
Wrong repo.
