### ISSUE TITLE
Call Sign String TypeError

### ISSUE THREAD

**Issue by JDaviso1** [SignalK/n2k-signalk#277]
There appears to be an issue with the Call Sign string. The error repeats in the log every six minutes.

TypeError: Cannot create property 'meta' on string 'WDN2119'
    at /usr/local/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:224:35
    at Array.reduce (<anonymous>)
    at addValue (/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:216:27)
    at addValues (/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:188:5)
    at FullSignalK.addUpdate (/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:110:5)
    at FullSignalK.addUpdates (/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:97:10)
    at FullSignalK.addDelta (/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:54:8)
    at DeltaChain.doProcess (/usr/local/lib/node_modules/signalk-server/lib/deltachain.js:15:18)
    at DeltaChain.process (/usr/local/lib/node_modules/signalk-server/lib/deltachain.js:11:21)
    at Server.app.handleMessage (/usr/local/lib/node_modules/signalk-server/lib/index.js:233:38)
    at Simple.<anonymous> (/usr/local/lib/node_modules/signalk-server/lib/pipedproviders.js:83:17)
    at Simple.emit (node:events:529:35)
    at Simple.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)

**Comment by gregsyoung** [comment]
same here ... every 6 minutes.

**Comment by tkurki** [comment]
I tried to recreate this, but failed. Could somebody please share a connection data log file when this happens?  Can be shared in private.

**Comment by gregsyoung** [comment]
yes, but will need some guidance on how to capture? a “connection data log”

**Comment by tkurki** [comment]
Have a look at https://github.com/SignalK/signalk-server/pull/1827/files

**Comment by sbender9** [comment]
I think we are setting callSignVhf incorrectly in the defaults, right?

<img width="1329" alt="image" src="https://github.com/user-attachments/assets/c03f0cfe-4de8-4863-bd71-c21eb1b6a134">
